<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="BaseProvider\BaseRepository.cs" />
    <Compile Remove="BaseProvider\ConnectionFactory.cs" />
    <Compile Remove="BaseProvider\Interface\IRepository.cs" />
    <Compile Remove="Utilities\JwtHelper.cs" />
  </ItemGroup>

  <ItemGroup>
	<FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Autofac" Version="8.0.0" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.8" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.0.1" />
    <PackageReference Include="StackExchange.Redis" Version="2.8.41" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.1" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.6.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\fd.infrastructure.entity\fd.infrastructure.entity.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="BaseProvider\Interface\" />
    <Folder Include="Middleware\" />
  </ItemGroup>

</Project>
